spring.application.name=gateway
server.port=8080

spring.cloud.gateway.server.webflux.routes[0].id=dummy-backend-status
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/status
spring.cloud.gateway.server.webflux.routes[0].filters[0]=TenantRateLimit

management.endpoints.web.exposure.include=health,info,gateway


spring.data.redis.host=localhost
spring.data.redis.port=6380

spring.datasource.url=jdbc:postgresql://localhost:5433/gateway
spring.datasource.username=gateway
spring.datasource.password=gateway

spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate