spring.application.name=gateway
spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration

server.port=8080

spring.cloud.gateway.server.webflux.routes[0].id=dummy-backend-status
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/status

management.endpoints.web.exposure.include=health,info,gateway
